
const $=id=>document.getElementById(id), G={lat:37.1773,lon:-3.5986}, MC=1.5;
let local=[], world=[], localMapObj=null, worldMapObj=null, selectedWorld=null, model=null, interacted=false, lastAlertState=false, sourceMeta={local:null,world:null,fetchedAt:null};
let localLatestMarker=null,worldLatestMarker=null,lastLatestLocalId=null,lastLatestWorldId=null;
let sensorRunning=false,sensorWakeLock=null,sensorCalibrating=false,sensorCalibration=[],sensorBaseline=.02,sensorSensitivity=2,sensorPersistStart=0,sensorLastAlert=0,sensorLastEvent=0,sensorHzSamples=[],sensorGravity={x:0,y:0,z:0},sensorUsingLinear=false;
let accHistory=[],gyroHistory=[],sensorWindow=[],sensorMaxPoints=180;
let selectedLocal=null,forecastHorizon=3,historyLocal=[],historyWorld=[],historyLoaded=false,historyMetrics=null;
let previousVisit=null,nightMode=false,nightEvents=[];
const VAPID_PUBLIC_KEY='BDjf8QsYspKoIrZ1l50L1WnWr3aJLgAhc-1I84LsKtFXBK_ZRdOPCn3XM88EROK8cp3pjN-ZX8TF8U8Jg_OqHJk';
let anonDeviceId;try{anonDeviceId=localStorage.getItem('sismia-device-v9');if(!anonDeviceId){anonDeviceId=(crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now());localStorage.setItem('sismia-device-v9',anonDeviceId)}}catch(_){anonDeviceId='session-'+Math.random().toString(36).slice(2)}
const towns=[['Granada',37.1773,-3.5986],['Alhendín',37.108,-3.645],['Gójar',37.104,-3.605],['La Zubia',37.119,-3.584],['Ogíjares',37.119,-3.607],['Villa de Otura',37.088,-3.633],['Armilla',37.143,-3.626],['Las Gabias',37.136,-3.670],['Dílar',37.073,-3.602],['Monachil',37.132,-3.538],['Cájar',37.133,-3.572],['Huétor Vega',37.145,-3.570],['Cenes de la Vega',37.160,-3.537],['Churriana de la Vega',37.145,-3.647],['Padul',37.024,-3.626],['Atarfe',37.224,-3.686],['Santa Fe',37.189,-3.718],['Albolote',37.230,-3.656],['Maracena',37.207,-3.634]];
function clamp(x,a,b){return Math.max(a,Math.min(b,x))}function rad(x){return x*Math.PI/180}function deg(x){return x*180/Math.PI}
function hav(a,b,c,d){const R=6371,p=rad(c-a),q=rad(d-b),x=Math.sin(p/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(q/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function age(t){const s=Math.max(0,(Date.now()-t)/1000);if(s<60)return Math.round(s)+' s';if(s<3600)return Math.round(s/60)+' min';if(s<86400)return (s/3600).toFixed(s<10800?1:0)+' h';return (s/86400).toFixed(1)+' d'}
function dateLocal(t){return new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(t))}
function nearestTown(lat,lon){let best=null;for(const t of towns){const d=hav(lat,lon,t[1],t[2]);if(!best||d<best.d)best={name:t[0],d}}return best}
function percentile(a,p){if(!a.length)return 0;let s=[...a].sort((x,y)=>x-y),i=(s.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return l===h?s[l]:s[l]+(s[h]-s[l])*(i-l)}
function median(a){return percentile(a,.5)}
function toast(t,p){$('toastT').textContent=t;$('toastP').textContent=p;$('toast').style.display='block';clearTimeout(toast._t);toast._t=setTimeout(()=>$('toast').style.display='none',3600)}
function severity(m){return m>=5?'FUERTE':m>=4?'MODERADO':m>=3?'PERCEPTIBLE':m>=2?'PEQUEÑO':'MICROSISMO'}
function quakeTone(m){return m>=5?'mag-deep':m>=4?'mag-red':m>=3?'mag-orange':m>=2?'mag-yellow':'mag-blue'}
function recentEventMarkup(e,index=0){const t=nearestTown(e.lat,e.lon),dG=hav(e.lat,e.lon,G.lat,G.lon),depth=Number.isFinite(e.depth)?e.depth.toFixed(1)+' km':'—',latest=index===0;return `<button class="recentEvent ${quakeTone(e.mag)} ${latest?'isLatest':''}" onclick="openLocal('${String(e.id).replaceAll("'","\\'")}')"><div class="recentMagnitude"><span>M</span><strong>${e.mag.toFixed(1)}</strong></div><div class="recentEventBody"><div class="recentEventTop"><b>${t.name}</b>${latest?'<em>ÚLTIMO</em>':''}</div><div class="recentEventMeta"><span><strong>${age(e.time)}</strong> hace</span><span>${dateLocal(e.time)}</span><span>Prof. <strong>${depth}</strong></span><span>${dG.toFixed(1)} km de Granada</span><span>${e.source}</span></div></div><span class="recentSeverity">${severity(e.mag)}</span></button>`}
function popupHTML(e){const town=nearestTown(e.lat,e.lon),dG=hav(e.lat,e.lon,G.lat,G.lon);return `<div class="popupMag">M${e.mag.toFixed(1)}</div><div class="popupPlace">${town.name}${town.d>1?' · '+town.d.toFixed(1)+' km':''}</div><div class="popupGrid"><div class="popupCell"><span>Hace</span><b>${age(e.time)}</b></div><div class="popupCell"><span>Hora local</span><b>${dateLocal(e.time)}</b></div><div class="popupCell"><span>Profundidad</span><b>${Number.isFinite(e.depth)?e.depth.toFixed(1)+' km':'—'}</b></div><div class="popupCell"><span>Clase</span><b>${severity(e.mag)}</b></div><div class="popupCell"><span>Dist. Granada</span><b>${dG.toFixed(1)} km</b></div><div class="popupCell"><span>Intensidad oficial</span><b>${e.intensity||'no incluida'}</b></div></div>`}
function circlePoly(lat,lon,rKm,n=64){const pts=[];for(let i=0;i<=n;i++){const br=2*Math.PI*i/n,dr=rKm/6371,la=rad(lat),lo=rad(lon);const la2=Math.asin(Math.sin(la)*Math.cos(dr)+Math.cos(la)*Math.sin(dr)*Math.cos(br));const lo2=lo+Math.atan2(Math.sin(br)*Math.sin(dr)*Math.cos(la),Math.cos(dr)-Math.sin(la)*Math.sin(la2));pts.push([deg(lo2),deg(la2)])}return {type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[pts]}}}
function eventFC(es){return {type:'FeatureCollection',features:es.map(e=>({type:'Feature',id:String(e.id),properties:{id:String(e.id),mag:e.mag,place:e.place,time:e.time,depth:e.depth,source:e.source},geometry:{type:'Point',coordinates:[e.lon,e.lat]}}))}}
function shiftLatLon(lat,lon,km,bearingDeg){const d=km/6371,br=rad(bearingDeg),la=rad(lat),lo=rad(lon),la2=Math.asin(Math.sin(la)*Math.cos(d)+Math.cos(la)*Math.sin(d)*Math.cos(br)),lo2=lo+Math.atan2(Math.sin(br)*Math.sin(d)*Math.cos(la),Math.cos(d)-Math.sin(la)*Math.sin(la2));return{lat:deg(la2),lon:deg(lo2)}}
function forecastProjection(h=forecastHorizon){if(!model)return{center:G,radius:6,events:[]};const b=model.migrationBearing??0,shift=Math.min(model.radius*.65,(model.migration||0)*Math.max(0.3,h/6)*.35),c=shiftLatLon(model.center.lat,model.center.lon,shift,b),radius=clamp(model.radius*(1+.18*h/24),3,32),events=(model.e24.length?model.e24:model.e72).map(e=>{const q=shiftLatLon(e.lat,e.lon,shift,b);return{...e,lat:q.lat,lon:q.lon}});return{center:c,radius,events}}
function snapshotNow(){if(!model)return null;return{at:Date.now(),events72:model.e72.length,events6:model.e6.length,max:model.max,score:model.score,center:model.center,radius:model.radius,p3:model.p3}}
function deltaText(v,suffix=''){if(!Number.isFinite(v))return'—';return`${v>0?'+':''}${typeof v==='number'&&Math.abs(v)<10?v.toFixed(1):Math.round(v)}${suffix}`}
function saveVisitSnapshot(){const snap=snapshotNow();if(snap)try{localStorage.setItem('sismia-last-visit-v9',JSON.stringify(snap))}catch(_){}}
function renderChanges(){const es=local.slice().sort((a,b)=>b.time-a.time).slice(0,5);$('changeBadge').textContent=es.length?`${es.length} ÚLTIMOS`:'SIN DATOS';$('changeGrid').innerHTML=es.map((e,i)=>recentEventMarkup(e,i)).join('')||'<div class="notice">No hay eventos locales disponibles.</div>'}
function renderScenarios(){if(!model)return;let decay=clamp(60-(model.accel-1)*28-model.p3*.18,8,88),persistent=clamp(28+Math.abs(model.accel-1)*18+model.e24*.25,8,75),escalation=clamp(8+model.p3*.35+Math.max(0,model.max-3)*9,3,65),sum=decay+persistent+escalation;decay=100*decay/sum;persistent=100*persistent/sum;escalation=100*escalation/sum;$('scenarioGrid').innerHTML=[['Decaimiento',decay,'Menor ritmo y progresiva relajación de la secuencia.'],['Persistencia',persistent,'Continúan microeventos/M2–M3 sin cambio brusco.'],['Escalada',escalation,'Aumenta el peso relativo de un evento significativamente mayor.']].map(x=>`<div class="scenario"><div class="pct">${Math.round(x[1])}%</div><b>${x[0]}</b><small>${x[2]} Peso heurístico, no probabilidad calibrada.</small></div>`).join('')}
function setForecastHorizon(h){forecastHorizon=Number(h)||3;document.querySelectorAll('#horizonBtns button').forEach(b=>b.classList.toggle('on',Number(b.dataset.h)===forecastHorizon));$('horizonBadge').textContent=(forecastHorizon===3?'0–3':forecastHorizon===6?'3–6':forecastHorizon===12?'6–12':'12–24')+' H';renderLocalMap()}
function dnaVector(m=model){if(!m)return[];return[['Frecuencia',clamp(m.rate/3,0,1),m.rate.toFixed(2)+'/h'],['Magnitud',clamp(m.max/5,0,1),'M'+m.max.toFixed(1)],['Superficial',clamp(m.shallow,0,1),Math.round(m.shallow*100)+'%'],['Cluster',clamp(1-m.radius/30,0,1),m.radius.toFixed(1)+' km'],['b-value',clamp((m.b||0)/1.8,0,1),m.b?m.b.toFixed(2):'N/D'],['Aceleración',clamp(m.accel/2.5,0,1),m.accel.toFixed(2)+'×']]}
function renderDNA(){if(!model)return;const v=dnaVector();$('dnaGrid').innerHTML=v.map(x=>`<div class="dnaCell"><span>${x[0]}</span><strong>${x[2]}</strong><div class="miniTrack"><i style="width:${Math.round(x[1]*100)}%"></i></div></div>`).join('')}


function newest(es){return es?.length?es.reduce((a,b)=>!a||b.time>a.time?b:a,null):null}
function latestMarkerElement(kind,e){const el=document.createElement('div');el.className='latest-seismo-marker '+(kind==='world'?'world':'local');el.setAttribute('aria-label',`Último seísmo ${kind==='world'?'mundial':'de Granada'}: magnitud ${e.mag.toFixed(1)}`);el.innerHTML='<span class="quake-wave w1"></span><span class="quake-wave w2"></span><span class="quake-core"></span><span class="quake-tag">ÚLTIMO</span>';return el}
function syncLatestMarker(kind,e,map){const markerKey=kind==='world'?'worldLatestMarker':'localLatestMarker';let marker=kind==='world'?worldLatestMarker:localLatestMarker;if(!e||!map){if(marker){marker.remove();if(kind==='world')worldLatestMarker=null;else localLatestMarker=null}return}
  const currentId=marker?.getElement()?.dataset?.eventId;
  if(!marker||String(currentId)!==String(e.id)){
    if(marker)marker.remove();
    const el=latestMarkerElement(kind,e);el.dataset.eventId=String(e.id);
    el.addEventListener('click',ev=>{ev.stopPropagation();if(kind==='world')selectWorld(String(e.id));else showLocalEvent(e)});
    marker=new maplibregl.Marker({element:el,anchor:'center'}).setLngLat([e.lon,e.lat]).addTo(map);
    if(kind==='world')worldLatestMarker=marker;else localLatestMarker=marker;
  }else marker.setLngLat([e.lon,e.lat]);
}
function updateLatestMarkers(){
  const le=newest(model?.e72||local.filter(e=>Date.now()-e.time<=72*36e5));
  const we=newest(world);
  if(localMapObj?.loaded())syncLatestMarker('local',le,localMapObj);
  if(worldMapObj?.loaded())syncLatestMarker('world',we,worldMapObj);
  if(le){if(lastLatestLocalId!==null&&String(lastLatestLocalId)!==String(le.id))toast('Nuevo seísmo en Granada',`M${le.mag.toFixed(1)} · ${nearestTown(le.lat,le.lon).name} · ${age(le.time)}`);lastLatestLocalId=le.id}
  if(we){if(lastLatestWorldId!==null&&String(lastLatestWorldId)!==String(we.id))toast('Nuevo seísmo mundial',`M${we.mag.toFixed(1)} · ${we.place}`);lastLatestWorldId=we.id}
}
function addGranada(map){if(map.getSource('granada'))return;map.addSource('granada',{type:'geojson',data:{type:'Feature',properties:{},geometry:{type:'Point',coordinates:[G.lon,G.lat]}}});map.addLayer({id:'granada-ring',type:'circle',source:'granada',paint:{'circle-radius':9,'circle-color':'rgba(88,230,255,.12)','circle-stroke-color':'#58e6ff','circle-stroke-width':2}});map.addLayer({id:'granada-label',type:'symbol',source:'granada',layout:{'text-field':'GRANADA','text-size':11,'text-offset':[0,1.6],'text-anchor':'top'},paint:{'text-color':'#dffbff','text-halo-color':'#071018','text-halo-width':1.5}})}
function addLocalLayers(map){if(map.getSource('local-quakes'))return;
map.addSource('local-quakes',{type:'geojson',data:eventFC([])});
map.addLayer({id:'local-heat',type:'heatmap',source:'local-quakes',maxzoom:12,paint:{'heatmap-weight':['interpolate',['linear'],['get','mag'],1,0.15,5,1],'heatmap-intensity':['interpolate',['linear'],['zoom'],7,.6,11,1.4],'heatmap-radius':['interpolate',['linear'],['zoom'],7,16,11,30],'heatmap-opacity':.28}});
map.addLayer({id:'local-points',type:'circle',source:'local-quakes',paint:{'circle-radius':['interpolate',['linear'],['get','mag'],1,4,3,7,5,13],'circle-color':['step',['get','mag'],'#73aef5',2,'#e8cf67',3,'#ee9b55',4,'#e96355',5,'#d93636'],'circle-stroke-color':'#fff5e9','circle-stroke-width':.9,'circle-opacity':.92}});
map.on('click','local-points',ev=>{const f=ev.features?.[0];if(!f)return;const e=local.find(x=>String(x.id)===String(f.properties.id));if(e)showLocalEvent(e)});
map.on('mouseenter','local-points',()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave','local-points',()=>map.getCanvas().style.cursor='');
map.addSource('forecast-zone',{type:'geojson',data:{type:'FeatureCollection',features:[]}});
map.addLayer({id:'forecast-zone-fill',type:'fill',source:'forecast-zone',paint:{'fill-color':'#58e6ff','fill-opacity':.07}});
map.addLayer({id:'forecast-zone-line',type:'line',source:'forecast-zone',paint:{'line-color':'#58e6ff','line-width':2,'line-dasharray':[3,2],'line-opacity':.8}});
}
function addWorldLayers(map){if(map.getSource('world-quakes'))return;map.addSource('world-quakes',{type:'geojson',data:eventFC([])});map.addLayer({id:'world-points',type:'circle',source:'world-quakes',paint:{'circle-radius':['interpolate',['linear'],['get','mag'],5.5,5,7,11,9,18],'circle-color':['step',['get','mag'],'#ffc45f',6.5,'#ff9e5f',7.5,'#ff6377'],'circle-stroke-color':'#fff','circle-stroke-width':.7,'circle-opacity':.85}});map.on('click','world-points',ev=>{const f=ev.features?.[0];if(!f)return;selectWorld(String(f.properties.id))});map.addSource('world-link',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'world-link-line',type:'line',source:'world-link',paint:{'line-color':'#58e6ff','line-width':2,'line-dasharray':[2,2],'line-opacity':.75}})}
function ensureLocalMap(){if(localMapObj)return localMapObj;if(!window.maplibregl){$('localMap').innerHTML='<div class="mapError">No se pudo cargar MapLibre. Comprueba Internet y recarga.</div>';return null}localMapObj=new maplibregl.Map({container:'localMap',style:'https://tiles.openfreemap.org/styles/dark',center:[-3.62,37.12],zoom:9.6,pitch:18,attributionControl:true});localMapObj.addControl(new maplibregl.NavigationControl(),'bottom-right');localMapObj.on('load',()=>{addGranada(localMapObj);addLocalLayers(localMapObj);renderLocalMap()});return localMapObj}
function ensureWorldMap(){if(worldMapObj)return worldMapObj;if(!window.maplibregl){$('worldMap').innerHTML='<div class="mapError">No se pudo cargar el mapa mundial.</div>';return null}worldMapObj=new maplibregl.Map({container:'worldMap',style:'https://tiles.openfreemap.org/styles/liberty',center:[8,25],zoom:1.2,attributionControl:true});worldMapObj.addControl(new maplibregl.NavigationControl({showCompass:false}),'bottom-right');worldMapObj.on('load',()=>{addGranada(worldMapObj);addWorldLayers(worldMapObj);renderWorldMap()});return worldMapObj}
function showLocalEvent(e){const m=ensureLocalMap();if(!m)return;selectedLocal=e;m.flyTo({center:[e.lon,e.lat],zoom:Math.max(m.getZoom(),11),essential:true});new maplibregl.Popup({offset:12,maxWidth:'310px'}).setLngLat([e.lon,e.lat]).setHTML(popupHTML(e)).addTo(m)}
window.openLocal=id=>{const e=local.find(x=>String(x.id)===String(id));if(e){document.querySelector('[data-view="now"]').click();setTimeout(()=>showLocalEvent(e),120)}};
function weightedCenter(es){if(!es.length)return {lat:G.lat,lon:G.lon};const now=Date.now();let sw=0,la=0,lo=0;for(const e of es){const ageH=Math.max(.05,(now-e.time)/36e5),w=(1+Math.max(0,e.mag-MC))*(1/(1+ageH/6));sw+=w;la+=e.lat*w;lo+=e.lon*w}return {lat:la/sw,lon:lo/sw}}
