async function getJSON(url){let r=await fetch(url,{cache:'no-store',headers:{'cache-control':'no-cache','pragma':'no-cache'}});let text=await r.text();let data;try{data=JSON.parse(text)}catch(_){throw new Error('Respuesta no JSON · HTTP '+r.status)}if(!r.ok)throw Object.assign(new Error('HTTP '+r.status),{payload:data});return data}
function cacheSave(){try{localStorage.setItem('sismia-live-cache-v6',JSON.stringify({local,world,sourceMeta,savedAt:Date.now()}))}catch(_){}}
function cacheRead(){try{return JSON.parse(localStorage.getItem('sismia-live-cache-v6')||'null')}catch(_){return null}}
function chip(id,state){const el=$(id);if(!el)return;el.classList.remove('ok','bad','cache');if(state)el.classList.add(state)}
function renderSourceMeta(){const lm=sourceMeta.local,wm=sourceMeta.world;let ltxt=lm?.ok?`online · ${local.length} eventos · ${lm.latencyMs||0} ms`:lm?.cached?`caché · ${local.length} eventos`:'error';let wtxt=wm?.ok?`online · ${world.length} eventos · ${wm.latencyMs||0} ms`:wm?.direct?`directo · ${world.length} eventos`:wm?.cached?`caché · ${world.length} eventos`:'error';$('localSourceText').textContent=ltxt;$('worldSourceText').textContent=wtxt;chip('localSourceChip',lm?.ok?'ok':lm?.cached?'cache':'bad');chip('worldSourceChip',wm?.ok||wm?.direct?'ok':wm?.cached?'cache':'bad');const stamp=sourceMeta.fetchedAt?`Última consulta: ${dateLocal(sourceMeta.fetchedAt)}`:'Sin actualización';$('lastUpdate').textContent=stamp;$('worldUpdateStamp').textContent=`${stamp} · Granada: ${local.length} · Mundo: ${world.filter(e=>e.mag>=5.5).length} M≥5,5`;$('worldLiveBadge').textContent=wm?.ok||wm?.direct?'USGS · EN VIVO':wm?.cached?'USGS · CACHÉ':'USGS · ERROR';$('feedState').textContent=(lm?.ok&&(wm?.ok||wm?.direct))?'EN VIVO':(lm?.ok||wm?.ok||wm?.direct)?'PARCIAL':'SIN CONEXIÓN';$('analysisState').textContent=lm?.ok?'EMSC LIVE':lm?.cached?'EMSC CACHÉ':'SIN DATOS'}
async function directWorldFallback(){const r=await fetch('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_week.geojson?_'+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('USGS directo '+r.status);const j=await r.json();return (j.features||[]).map(f=>({id:f.id,time:Number(f.properties?.time),mag:Number(f.properties?.mag)||0,place:f.properties?.place||'Sin localización',lon:Number(f.geometry?.coordinates?.[0]),lat:Number(f.geometry?.coordinates?.[1]),depth:Number(f.geometry?.coordinates?.[2]),source:'USGS',intensity:f.properties?.mmi??null})).filter(e=>Number.isFinite(e.time)&&Number.isFinite(e.lat)&&Number.isFinite(e.lon))}
function setRefreshing(on){for(const id of ['refresh','refreshWorld']){const b=$(id);if(!b)continue;b.classList.toggle('refreshing',on);b.disabled=on;if(id==='refresh')b.textContent=on?'CONSULTANDO INTERNET…':'ACTUALIZAR AHORA';else b.textContent=on?'CONSULTANDO USGS + EMSC…':'↻ ACTUALIZAR MUNDO + GRANADA'}}
async function load(force=false){setRefreshing(true);$('feedState').textContent='ACTUALIZANDO';const cached=cacheRead();let payload=null;try{payload=await getJSON('/api/earthquakes?scope=sync&_='+Date.now())}catch(e){console.warn('sync backend',e)}let localFresh=false,worldFresh=false;if(payload){sourceMeta.fetchedAt=payload.fetchedAt||Date.now();sourceMeta.local=payload.local||{ok:false};sourceMeta.world=payload.world||{ok:false};if(payload.local?.ok){local=payload.local.events||[];localFresh=true}if(payload.world?.ok){world=payload.world.events||[];worldFresh=true}}if(!worldFresh){try{world=await directWorldFallback();worldFresh=true;sourceMeta.world={ok:false,direct:true,source:'USGS'};sourceMeta.fetchedAt=Date.now()}catch(e){console.warn('world direct',e)}}if(!localFresh&&cached?.local?.length){local=cached.local;sourceMeta.local={...(sourceMeta.local||{}),ok:false,cached:true}}if(!worldFresh&&cached?.world?.length){world=cached.world;sourceMeta.world={...(sourceMeta.world||{}),ok:false,cached:true}}if(localFresh||worldFresh)cacheSave();if(selectedWorld){selectedWorld=world.find(e=>String(e.id)===String(selectedWorld.id))||null}model=calcModel();renderNow();renderWorldList();renderAnalysis();renderSourceMeta();updateLatestMarkers();setRefreshing(false);if(force){if(localFresh&&worldFresh)toast('Datos actualizados','EMSC y USGS consultados ahora mismo. Correlaciones recalculadas.');else if(localFresh||worldFresh)toast('Actualización parcial','Una fuente respondió y la otra usa respaldo/caché. Revisa los indicadores.');else toast('No se pudo actualizar','Se mantienen los últimos datos guardados, si estaban disponibles.')}if(!local.length)toast('Sin catálogo local','EMSC no devolvió eventos y no existe caché local todavía.')}

function sensorThresholdValue(){const bases={1:.26,2:.15,3:.08};return Math.max(bases[sensorSensitivity]||.15,sensorBaseline*5.5)}
function sensorElsUpdateThreshold(){const t=sensorThresholdValue();$('sensorThreshold').textContent=t.toFixed(3)+' m/s²';$('sensitivityLabel').textContent=sensorSensitivity===1?'BAJA':sensorSensitivity===3?'ALTA':'MEDIA'}
function zeroMotionCharts(){accHistory=[];gyroHistory=[];sensorWindow=[];drawMotionChart('accChart',accHistory,1);drawMotionChart('gyroChart',gyroHistory,12)}
function motionValue(v){return Number.isFinite(Number(v))?Number(v):0}
function addMotionPoint(arr,p){arr.push(p);if(arr.length>sensorMaxPoints)arr.splice(0,arr.length-sensorMaxPoints)}
function motionStats(){const now=performance.now(),win=sensorWindow.filter(x=>now-x.t<=1500);sensorWindow=win;if(!win.length)return{rms:0,peak:0,gyro:0,stable:1};const rms=Math.sqrt(win.reduce((s,x)=>s+x.a*x.a,0)/win.length);const peak=Math.max(...win.map(x=>x.a));const gyro=Math.sqrt(win.reduce((s,x)=>s+x.g*x.g,0)/win.length);const stable=win.filter(x=>x.g<5).length/win.length;return{rms,peak,gyro,stable}}
function drawMotionChart(id,data,defaultRange){const c=$(id);if(!c)return;const rect=c.getBoundingClientRect();if(!rect.width)return;const dpr=Math.min(window.devicePixelRatio||1,2),w=Math.round(rect.width*dpr),h=Math.round(rect.height*dpr);if(c.width!==w||c.height!==h){c.width=w;c.height=h}const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);const W=rect.width,H=rect.height;ctx.clearRect(0,0,W,H);ctx.fillStyle='#071018';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#172533';ctx.lineWidth=1;for(let i=1;i<5;i++){let y=H*i/5;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}const max=Math.max(defaultRange,...data.flatMap(p=>[Math.abs(p.x),Math.abs(p.y),Math.abs(p.z)]))*1.15||defaultRange;ctx.strokeStyle='#2a394b';ctx.beginPath();ctx.moveTo(0,H/2);ctx.lineTo(W,H/2);ctx.stroke();const styles=[['x','#58e6ff'],['y','#ffc45f'],['z','#b89cff']];for(const [key,col] of styles){ctx.strokeStyle=col;ctx.lineWidth=1.6;ctx.beginPath();data.forEach((p,i)=>{const x=data.length<=1?0:i/(sensorMaxPoints-1)*W;const y=H/2-(p[key]/max)*(H*.43);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.stroke()}ctx.fillStyle='#718196';ctx.font='9px -apple-system';ctx.fillText('+'+max.toFixed(defaultRange<2?2:0),6,12);ctx.fillText('−'+max.toFixed(defaultRange<2?2:0),6,H-7)}
function sensorRender(stats){const t=sensorThresholdValue(),score=Math.max(0,Math.min(100,(stats.rms/t)*72+(stats.peak/t)*18+(stats.stable)*10));$('vibeRms').textContent=stats.rms.toFixed(3);$('vibePeak').textContent=stats.peak.toFixed(3);$('gyroRms').textContent=stats.gyro.toFixed(1)+'°';$('vibeGauge').style.width=Math.min(100,score)+'%';$('stablePct').textContent=Math.round(stats.stable*100)+'%';$('vibeScore').textContent=Math.round(score)+'/100';$('sampleHz').textContent=(sensorHzSamples.length?Math.round(sensorHzSamples.length/(Math.max(1,(sensorHzSamples.at(-1)-sensorHzSamples[0])/1000))):0)+' Hz';let persistent=sensorPersistStart?Math.max(0,performance.now()-sensorPersistStart):0;$('persistMs').textContent=Math.round(persistent)+' ms';let mode='ESTABLE',cls='good',state='MONITORIZANDO',sub='Teléfono aparentemente apoyado. Analizando vibración ambiental.';if(stats.gyro>8||stats.stable<.6){mode='TELÉFONO EN MOVIMIENTO';cls='warn';state='MOVIMIENTO DEL TELÉFONO';sub='La rotación es alta; esta señal no se utilizará como indicio de vibración ambiental.'}else if(stats.rms>t){mode='VIBRACIÓN ELEVADA';cls='bad';state='VIBRACIÓN DETECTADA';sub='La aceleración supera el umbral dinámico con rotación relativamente baja.'}else if(stats.rms>t*.55){mode='VIBRACIÓN MODERADA';cls='warn';state='VIBRACIÓN MODERADA';sub='Hay movimiento por encima del ruido base, todavía bajo el umbral de alerta.'}$('sensorMode').textContent=mode;$('sensorMode').className='sensorMode '+cls;$('sensorState').textContent=state;$('sensorSub').textContent=sub;$('accBadge').textContent=sensorUsingLinear?'LINEAL':'FILTRO GRAVEDAD';$('gyroBadge').textContent=sensorRunning?'LIVE':'EN ESPERA';$('sensorExplanation').innerHTML=stats.gyro>8?'SISMIA detecta que el iPhone está siendo <b>cogido, girado o desplazado</b>. Aunque la aceleración sea alta, no generará una alerta de posible temblor mientras predomine este patrón.':stats.rms>t?`La señal supera el umbral dinámico de <b>${t.toFixed(3)} m/s²</b>. Para alertar debe mantenerse durante aproximadamente 0,8 s y el teléfono debe conservar poca rotación.`:`Ruido actual ${stats.rms.toFixed(3)} m/s² frente a umbral ${t.toFixed(3)} m/s². Coloca el iPhone sobre una superficie rígida para obtener una lectura más útil.`;drawMotionChart('accChart',accHistory,Math.max(.3,t*2));drawMotionChart('gyroChart',gyroHistory,20);if(stats.rms>t&&stats.gyro<8&&stats.stable>.65){if(!sensorPersistStart)sensorPersistStart=performance.now();if(performance.now()-sensorPersistStart>800&&Date.now()-sensorLastAlert>15000){sensorLastAlert=Date.now();sensorLocalAlert(stats,t)}}else sensorPersistStart=0}
async function sensorLocalAlert(stats,t){recordNightPeak(stats);sendSensorHit(stats);$('sensorAlarm').classList.add('on');$('sensorAlarmTitle').textContent='VIBRACIÓN LOCAL INTENSA';$('sensorAlarmText').textContent=`RMS ${stats.rms.toFixed(3)} m/s² · umbral ${t.toFixed(3)} · giro ${stats.gyro.toFixed(1)}°/s. Esto no confirma un terremoto.`;$('networkVerify').textContent='CONSULTANDO…';$('networkVerifyText').textContent='Actualizando EMSC + USGS para buscar contexto oficial.';triggerAlert('Vibración intensa detectada','El iPhone ha registrado vibración sostenida con baja rotación. No confirma un terremoto.');try{await load(false);const latest=[...local].sort((a,b)=>b.time-a.time)[0];if(latest&&Date.now()-latest.time<10*60*1000){$('networkVerify').textContent='EVENTO RECIENTE EN CATÁLOGO';$('networkVerifyText').textContent=`Último catálogo: M${latest.mag.toFixed(1)} · ${latest.place} · ${age(latest.time)}. La coincidencia temporal no demuestra que sea la causa.`}else{$('networkVerify').textContent='SIN CONFIRMACIÓN RECIENTE';$('networkVerifyText').textContent='No aparece todavía un evento local reciente en el catálogo consultado. Puede existir latencia de publicación.'}}catch(_){$('networkVerify').textContent='RED NO DISPONIBLE';$('networkVerifyText').textContent='No se pudo verificar la señal con las fuentes online.'}setTimeout(()=>$('sensorAlarm').classList.remove('on'),10000)}
function processDeviceMotion(e){if(!sensorRunning)return;const now=performance.now();sensorLastEvent=now;sensorHzSamples.push(now);while(sensorHzSamples.length&&now-sensorHzSamples[0]>2000)sensorHzSamples.shift();let a=e.acceleration, x=0,y=0,z=0;sensorUsingLinear=!!(a&&[a.x,a.y,a.z].some(v=>v!==null&&v!==undefined));if(sensorUsingLinear){x=motionValue(a.x);y=motionValue(a.y);z=motionValue(a.z)}else{const ag=e.accelerationIncludingGravity||{};const rx=motionValue(ag.x),ry=motionValue(ag.y),rz=motionValue(ag.z),alpha=.08;sensorGravity.x=(1-alpha)*sensorGravity.x+alpha*rx;sensorGravity.y=(1-alpha)*sensorGravity.y+alpha*ry;sensorGravity.z=(1-alpha)*sensorGravity.z+alpha*rz;x=rx-sensorGravity.x;y=ry-sensorGravity.y;z=rz-sensorGravity.z}const rr=e.rotationRate||{};const gx=motionValue(rr.beta),gy=motionValue(rr.gamma),gz=motionValue(rr.alpha);const am=Math.sqrt(x*x+y*y+z*z),gm=Math.sqrt(gx*gx+gy*gy+gz*gz);addMotionPoint(accHistory,{x,y,z,t:now});addMotionPoint(gyroHistory,{x:gx,y:gy,z:gz,t:now});sensorWindow.push({a:am,g:gm,t:now});if(sensorCalibrating)sensorCalibration.push(am);sensorRender(motionStats())}
async function requestMotionPermission(){if(typeof DeviceMotionEvent==='undefined')throw new Error('Este dispositivo/navegador no expone DeviceMotionEvent.');if(typeof DeviceMotionEvent.requestPermission==='function'){const p=await DeviceMotionEvent.requestPermission();if(p!=='granted')throw new Error('Permiso de movimiento no concedido.')}return true}
async function startSensors(){if(sensorRunning){stopSensors();return}try{await requestMotionPermission();sensorRunning=true;window.addEventListener('devicemotion',processDeviceMotion,true);$('startSensors').textContent='DETENER SENSORES';$('recordDot').classList.add('on');$('recordText').textContent='LIVE';$('sensorState').textContent='MONITORIZANDO';$('sensorSub').textContent='Coloca el iPhone apoyado e inmóvil para detectar vibración ambiental.';$('sensorMode').textContent='INICIANDO';$('accBadge').textContent='LIVE';$('gyroBadge').textContent='LIVE';zeroMotionCharts();setTimeout(()=>{if(sensorRunning&&performance.now()-sensorLastEvent>2500){$('sensorState').textContent='SIN LECTURAS';$('sensorSub').textContent='El permiso está activo pero Safari no está entregando muestras. Comprueba que abriste SISMIA en Safari/PWA por HTTPS.'}},2800)}catch(e){toast('Sensores no disponibles',e.message||String(e));$('sensorState').textContent='PERMISO NECESARIO';$('sensorSub').textContent=e.message||'No se pudo activar el sensor.'}}
function stopSensors(){sensorRunning=false;window.removeEventListener('devicemotion',processDeviceMotion,true);$('startSensors').textContent='ACTIVAR SENSORES';$('recordDot').classList.remove('on');$('recordText').textContent='OFF';$('sensorState').textContent='SENSORES DETENIDOS';$('sensorMode').textContent='OFF';$('sensorMode').className='sensorMode';$('accBadge').textContent='EN ESPERA';$('gyroBadge').textContent='EN ESPERA';sensorPersistStart=0}
async function calibrateSensor(){if(!sensorRunning){toast('Activa primero los sensores','Después deja el iPhone inmóvil y pulsa CALIBRAR.');return}sensorCalibration=[];sensorCalibrating=true;$('calibrateSensor').textContent='CALIBRANDO… NO TOCAR';$('baselineText').textContent='Midiendo ruido durante 3 segundos…';setTimeout(()=>{sensorCalibrating=false;if(sensorCalibration.length){sensorBaseline=Math.sqrt(sensorCalibration.reduce((s,v)=>s+v*v,0)/sensorCalibration.length);$('baselineText').textContent='Ruido base RMS: '+sensorBaseline.toFixed(3)+' m/s²';sensorElsUpdateThreshold();toast('Calibración terminada','Umbral adaptado al ruido de la superficie.')}else $('baselineText').textContent='No se recibieron muestras durante la calibración.';$('calibrateSensor').textContent='CALIBRAR 3 s'},3000)}
async function toggleWakeLock(){try{if(sensorWakeLock){await sensorWakeLock.release();sensorWakeLock=null;$('wakeSensor').textContent='MANTENER PANTALLA ACTIVA';return}if(!navigator.wakeLock?.request)throw new Error('Wake Lock no disponible en este navegador.');sensorWakeLock=await navigator.wakeLock.request('screen');$('wakeSensor').textContent='PANTALLA ACTIVA ✓';sensorWakeLock.addEventListener('release',()=>{$('wakeSensor').textContent='MANTENER PANTALLA ACTIVA';sensorWakeLock=null})}catch(e){toast('Pantalla activa',e.message||'No disponible.')}}

function readNightEvents(){try{nightEvents=JSON.parse(localStorage.getItem('sismia-night-log-v9')||'[]')}catch(_){nightEvents=[]};renderNightLog()}
function renderNightLog(){if(!$('nightLog'))return;$('nightLog').innerHTML=nightEvents.length?nightEvents.slice().reverse().slice(0,30).map(x=>`<div><b>${dateLocal(x.at)}</b> · RMS ${x.rms.toFixed(3)} · pico ${x.peak.toFixed(3)} · giro ${x.gyro.toFixed(1)}°/s${x.catalog?' · '+x.catalog:''}</div>`).join(''):'<div>Sin picos registrados todavía.</div>'}
function recordNightPeak(stats,catalog=''){nightEvents.push({at:Date.now(),rms:stats.rms,peak:stats.peak,gyro:stats.gyro,catalog});nightEvents=nightEvents.slice(-100);try{localStorage.setItem('sismia-night-log-v9',JSON.stringify(nightEvents))}catch(_){}renderNightLog()}
async function toggleNightMode(){nightMode=!nightMode;document.body.classList.toggle('nightActive',nightMode);$('nightModeBtn').textContent=nightMode?'SALIR DE MODO NOCHE':'ACTIVAR MODO NOCHE';if(nightMode){if(!sensorRunning)await startSensors();if(!sensorWakeLock)await toggleWakeLock();toast('Modo noche activo','Mantén el iPhone apoyado y la PWA en primer plano. iOS puede suspender sensores si bloqueas la pantalla.')}else if(sensorWakeLock){try{await sensorWakeLock.release()}catch(_){}}}
function sensorResize(){drawMotionChart('accChart',accHistory,Math.max(.3,sensorThresholdValue()*2));drawMotionChart('gyroChart',gyroHistory,20)}

try{previousVisit=JSON.parse(localStorage.getItem('sismia-last-visit-v9')||'null')}catch(_){previousVisit=null}
document.addEventListener('pointerdown',()=>{interacted=true},{once:true});
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('on'));b.classList.add('on');$(b.dataset.view).classList.add('on');requestAnimationFrame(()=>{if(b.dataset.view==='now')ensureLocalMap()?.resize();if(b.dataset.view==='world')ensureWorldMap()?.resize();if(b.dataset.view==='analysis'){renderAnalysis();loadHistory(false)}if(b.dataset.view==='alerts'){renderAlerts();pushStatus()}if(b.dataset.view==='vibration')sensorResize()})});
const refreshBtn=$('refresh');if(refreshBtn)refreshBtn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(!refreshBtn.disabled)load(true)},{passive:false});const refreshWorldBtn=$('refreshWorld');if(refreshWorldBtn)refreshWorldBtn.addEventListener('click',e=>{e.preventDefault();if(!refreshWorldBtn.disabled)load(true)},{passive:false});$('testAlarm').onclick=()=>alarm(true);$('askNotify').onclick=notify;$('startSensors').onclick=startSensors;$('calibrateSensor').onclick=calibrateSensor;$('wakeSensor').onclick=toggleWakeLock;$('sensorSensitivity').oninput=e=>{sensorSensitivity=Number(e.target.value);sensorElsUpdateThreshold()};
$('loadHistory').onclick=()=>loadHistory(true);$('nightModeBtn').onclick=toggleNightMode;$('clearNightLog').onclick=()=>{nightEvents=[];try{localStorage.removeItem('sismia-night-log-v9')}catch(_){}renderNightLog()};
document.querySelectorAll('#horizonBtns button').forEach(b=>b.onclick=()=>setForecastHorizon(Number(b.dataset.h)));document.querySelectorAll('[data-felt]').forEach(b=>b.onclick=()=>submitFelt(Number(b.dataset.felt)));
window.addEventListener('resize',sensorResize);window.addEventListener('pagehide',saveVisitSnapshot);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')saveVisitSnapshot()});
if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('/service-worker.js?v=9-vercel-rebuild').catch(console.warn);
sensorElsUpdateThreshold();readNightEvents();ensureLocalMap();load(false).then(()=>{loadCommunity();loadSensorNetwork();pushStatus()});setInterval(()=>load(false),60000);setInterval(()=>{pushStatus();loadSensorNetwork()},300000);
