function bearing(a,b,c,d){const y=Math.sin(rad(d-b))*Math.cos(rad(c)),x=Math.cos(rad(a))*Math.sin(rad(c))-Math.sin(rad(a))*Math.cos(rad(c))*Math.cos(rad(d-b));return (deg(Math.atan2(y,x))+360)%360}
function compass(x){return ['N','NE','E','SE','S','SO','O','NO'][Math.round(x/45)%8]}
function bValue(es){const m=es.filter(e=>e.mag>=MC).map(e=>e.mag);if(m.length<15)return null;const mean=m.reduce((a,b)=>a+b,0)/m.length,den=mean-(MC-.05);return den>0?Math.log10(Math.E)/den:null}
function probability(rate,h){return clamp(100*(1-Math.exp(-Math.max(0,rate)*h)),0,99.5)}
function calcModel(){const now=Date.now(),mags=local.filter(e=>e.mag>=MC),e72=mags.filter(e=>now-e.time<=72*36e5),e24=mags.filter(e=>now-e.time<=24*36e5),e12=mags.filter(e=>now-e.time<=12*36e5),e6=mags.filter(e=>now-e.time<=6*36e5),prev6=mags.filter(e=>now-e.time>6*36e5&&now-e.time<=12*36e5);const max=e72.length?Math.max(...e72.map(e=>e.mag)):0,depths=e72.map(e=>e.depth).filter(Number.isFinite),med=median(depths),rate6=e6.length/6,rate24=e24.length/24,rate=Math.max(.01,.65*rate6+.35*rate24),accel=prev6.length?e6.length/prev6.length:e6.length?2:1,b=bValue(e72),rate15=rate,rate3=b?rate*Math.pow(10,-b*(3-MC)):rate*(e72.filter(e=>e.mag>=3).length/Math.max(1,e72.length)),rate4=b?rate*Math.pow(10,-b*(4-MC)):rate*(e72.filter(e=>e.mag>=4).length/Math.max(1,e72.length));const center=weightedCenter(e24.length?e24:e72),dists=(e24.length?e24:e72).map(e=>hav(center.lat,center.lon,e.lat,e.lon)),radius=clamp(percentile(dists,.8)||5,3,25),recentC=weightedCenter(e6),priorC=weightedCenter(mags.filter(e=>now-e.time>6*36e5&&now-e.time<=24*36e5)),migration=(e6.length>=2&&e24.length-e6.length>=2)?hav(priorC.lat,priorC.lon,recentC.lat,recentC.lon):0,migrationBearing=migration?bearing(priorC.lat,priorC.lon,recentC.lat,recentC.lon):0,migDir=migration?compass(migrationBearing):'—';const shallow=depths.length?depths.filter(d=>d<=10).length/depths.length:0;const clusterScore=clamp(15*(1-radius/25),0,15),rateScore=clamp(e6.length*2.2,0,30),magScore=clamp(Math.max(0,max-2)*10,0,20),accelScore=clamp((accel-1)*10+5,0,15),depthScore=clamp(shallow*10,0,10);const strongestRemote=world.length?Math.max(0,...world.filter(e=>e.mag>=6).map(e=>remoteMetrics(e).screen)):0,remoteScore=clamp(strongestRemote/10,0,10);const score=Math.round(clamp(rateScore+magScore+accelScore+clusterScore+depthScore+remoteScore,0,100));const p15=probability(rate15,24),p3=probability(rate3,24),p4=probability(rate4,24),medianWait=rate15>0?Math.log(2)/rate15:null;model={now,e72,e24,e12,e6,prev6,max,med,rate6,rate24,rate,accel,b,center,radius,migration,migrationBearing,migDir,shallow,score,p15,p3,p4,medianWait,components:{'Actividad reciente':rateScore,'Magnitud máxima':magScore,'Cambio de ritmo':accelScore,'Concentración espacial':clusterScore,'Profundidad superficial':depthScore,'Influencia mundial screening':remoteScore}};return model}
function renderLocalMap(){const es=(model?.e72||local.filter(e=>Date.now()-e.time<=72*36e5));if($('localCountMap'))$('localCountMap').textContent=es.length+' eventos';if($('fullLocalCount'))$('fullLocalCount').textContent=es.length+' eventos · 72 h';const latest=newest(es);[localMapObj,fullLocalMapObj].filter(Boolean).forEach(m=>{const src=m.getSource?.('local-quakes');if(!src)return;src.setData(eventFC(es));const zone=m.getSource?.('cluster-zone');if(zone)zone.setData(model?{type:'FeatureCollection',features:[circlePoly(model.center.lat,model.center.lon,model.radius)]}:emptyFC());if(selectedLocal&&es.some(x=>String(x.id)===String(selectedLocal.id)))setSelectedLocalPoint(m,selectedLocal);syncLatestMarker('local',latest,m)})}
/* Antes solo se dibujaban los M≥5,5: con todo el feed USGS (M≥4,5) el mapa de
   calor mundial tiene datos suficientes para ser informativo y los "5 últimos"
   coinciden con lo que se ve en el mapa. */
function renderWorldMap(){const m=ensureWorldMap();if(!m)return;const src=m.getSource?.('world-quakes');if(!src)return;src.setData(eventFC(world));syncLatestMarker('world',newest(world),m);if(selectedWorld){setSelectedLocalPoint(m,selectedWorld);drawWorldLink(selectedWorld)}}
function drawWorldLink(e){const m=ensureWorldMap();if(!m)return;const src=m.getSource?.('world-link');if(!src)return;let coords=[],steps=40;for(let i=0;i<=steps;i++){const t=i/steps;coords.push([e.lon+(G.lon-e.lon)*t,e.lat+(G.lat-e.lat)*t])}src.setData({type:'FeatureCollection',features:[{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:coords}}]})}
function renderNow(){if(!model)return;$('score').style.setProperty('--score',model.score);$('scoreN').textContent=model.score;$('k72').textContent=model.e72.length;$('k6').textContent=model.e6.length;$('kmax').textContent=model.max?'M'+model.max.toFixed(1):'—';$('kdepth').textContent=model.med?model.med.toFixed(1)+' km':'—';let st=model.score>=80?'MUY ELEVADA':model.score>=60?'ELEVADA':model.score>=35?'MODERADA':'NORMAL';$('status').textContent=st;$('trend').textContent=model.accel>1.35?'↑ ritmo reciente aumentando':model.accel<.75?'↓ ritmo reciente descendiendo':'→ ritmo relativamente estable';const town=nearestTown(model.center.lat,model.center.lon);$('forecastPlace').textContent=town.name;$('forecastText').textContent=`Concentración reciente en un radio aproximado de ${model.radius.toFixed(1)} km · ${model.e24.length} eventos M≥1,5 en 24 h.`;$('forecastBadge').textContent=model.e24.length+' · 24 H';renderLocalList();renderLocalMap();renderChanges()}
let localListRangeDays=1,localIntensityFilter='all';
window.setLocalListRange=days=>{localListRangeDays=[1,3,7,30].includes(Number(days))?Number(days):1;document.querySelectorAll('#localRangeFilters button').forEach(b=>b.classList.toggle('on',Number(b.dataset.days)===localListRangeDays));renderLocalList()};
function intensityBucket(m){return m>=5?'strong':m>=4?'moderate':m>=3?'perceptible':m>=2?'small':'micro'}
window.setLocalIntensityFilter=cat=>{localIntensityFilter=['all','micro','small','perceptible','moderate','strong'].includes(cat)?cat:'all';document.querySelectorAll('#localIntensityFilters button').forEach(b=>b.classList.toggle('on',b.dataset.cat===localIntensityFilter));renderLocalList()};
function detailedLocalEventMarkup(e,isLatest=false){const t=nearestTown(e.lat,e.lon),dG=hav(e.lat,e.lon,G.lat,G.lon),depth=Number.isFinite(e.depth)?e.depth.toFixed(1)+' km':'—';return `<button class="event quakeEvent ${quakeTone(e.mag)} ${isLatest?'isLatest':''}" onclick="openLocal('${String(e.id).replaceAll("'","\\'")}')"><div class="quakeMagnitude"><span>M</span><strong>${e.mag.toFixed(1)}</strong></div><div class="quakeMain"><div class="quakeTitleRow"><b>${t.name}</b><span class="quakeClass">${severity(e.mag)}</span></div><div class="quakeTime"><strong>${age(e.time)} hace</strong><span>${dateLocal(e.time)}</span></div><div class="quakeFacts"><span><small>Profundidad</small><b>${depth}</b></span><span><small>Dist. Granada</small><b>${dG.toFixed(1)} km</b></span><span><small>Fuente</small><b>${e.source}</b></span></div></div>${isLatest?'<em class="latestEventFlag">ÚLTIMO</em>':''}</button>`}
function renderLocalList(){const now=Date.now(),all=local.slice().sort((a,b)=>b.time-a.time),cutoff=now-localListRangeDays*864e5,periodEvents=all.filter(e=>e.time>=cutoff),es=localIntensityFilter==='all'?periodEvents:periodEvents.filter(e=>intensityBucket(e.mag)===localIntensityFilter),latest=all[0]||null,label=localListRangeDays===1?'últimas 24 h':localListRangeDays===3?'últimos 3 días':localListRangeDays===7?'última semana':'último mes',catLabel={all:'todas las categorías',micro:'microsismos · M<2',small:'pequeños · M2–2,9',perceptible:'perceptibles · M3–3,9',moderate:'moderados · M4–4,9',strong:'fuertes · M≥5'}[localIntensityFilter];document.querySelectorAll('#localRangeFilters button').forEach(b=>b.classList.toggle('on',Number(b.dataset.days)===localListRangeDays));document.querySelectorAll('#localIntensityFilters button').forEach(b=>b.classList.toggle('on',b.dataset.cat===localIntensityFilter));$('allLocalSummary').textContent=`${es.length} eventos · ${label} · ${catLabel}`;$('localList').innerHTML=es.map(e=>detailedLocalEventMarkup(e,latest&&String(e.id)===String(latest.id))).join('')||`<div class="notice">No hay terremotos de esta categoría en ${label}.</div>`}

function remoteMetrics(e){const d=hav(G.lat,G.lon,e.lat,e.lon),arrival=e.time+(d/3.5)*1000,ageH=(Date.now()-e.time)/36e5,localM=local.filter(x=>x.mag>=MC);const c6=localM.filter(x=>x.time>=arrival&&x.time<arrival+6*36e5).length,c24=localM.filter(x=>x.time>=arrival+6*36e5&&x.time<arrival+24*36e5).length,c72=localM.filter(x=>x.time>=arrival+24*36e5&&x.time<arrival+72*36e5).length,rate7=localM.filter(x=>Date.now()-x.time<=168*36e5).length/168,exp24=Math.max(.25,rate7*24),ratio=(c6+c24)/exp24;let physical=clamp((e.mag-6)*22 + 38 - 8*Math.log10(Math.max(500,d)) - Math.max(0,ageH-24)*.25,0,70),temporal=clamp((ratio-1)*15,0,30),screen=Math.round(clamp(physical+temporal,0,100));return {d,arrival,c6,c24,c72,rate7,exp24,ratio,physical,temporal,screen}}
function selectWorld(id){const e=world.find(x=>String(x.id)===String(id));if(!e)return;selectedWorld=e;const r=remoteMetrics(e),m=ensureWorldMap();if(m){
  /* Sustituye al antiguo Popup de MapLibre (que además se apilaba en cada clic):
     ahora usa la misma ficha lateral que el mapa de Granada. */
  if(worldPopup){try{worldPopup.remove()}catch(_){}worldPopup=null}
  showWorldEvent(e,m);
  const mobile=window.innerWidth<=760,padding=mobile?{top:24,right:16,bottom:200,left:16}:{top:24,right:24,bottom:40,left:350};
  try{m.easeTo({center:[e.lon,e.lat],zoom:Math.max(2.2,m.getZoom()),padding,duration:430,essential:true})}catch(_){try{m.flyTo({center:[e.lon,e.lat],zoom:Math.max(2.2,m.getZoom()),essential:true})}catch(__){}}
  drawWorldLink(e)}$('corrScore').textContent=r.screen+'/100';$('corrEvent').innerHTML=`<b>M${e.mag.toFixed(1)} · ${safeMapText(e.place)}</b><br>${dateLocal(e.time)} · ${Math.round(r.d).toLocaleString('es-ES')} km de Granada.<br>Ondas superficiales ~3,5 km/s: llegada estimada a Granada ${dateLocal(r.arrival)}.`;$('corr6').textContent=r.c6;$('corr24').textContent=r.c24;$('corr72').textContent=r.c72;let txt=r.ratio>=2&&r.c6+r.c24>=3?`Hay un exceso temporal aparente (${r.ratio.toFixed(1)}× frente al fondo) tras la llegada estimada de las ondas. Es una señal para estudiar, no evidencia de causalidad.`:r.ratio>=1.2?`La coincidencia temporal es algo superior al fondo (${r.ratio.toFixed(1)}×), pero no permite inferir que el terremoto remoto haya desencadenado actividad en Granada.`:`No aparece un exceso temporal claro respecto al fondo (${r.ratio.toFixed(1)}×).`;$('corrConclusion').textContent=txt;renderAnalysis();}
window.selectWorld=selectWorld;
function renderWorldList(){const es=world.filter(e=>e.mag>=5.5).slice().sort((a,b)=>b.mag-a.mag||b.time-a.time),big=es[0];$('worldMax').textContent=big?'M'+big.mag.toFixed(1):'—';$('worldPlace').textContent=big?.place||'sin datos';$('worldList').innerHTML=es.slice(0,20).map(e=>{const r=remoteMetrics(e);return `<div class="event" onclick="selectWorld('${String(e.id).replaceAll("'","\\'")}')"><div class="mag">${e.mag.toFixed(1)}</div><div><b>${safeMapText(e.place)}</b><small>${age(e.time)} · ${Math.round(r.d).toLocaleString('es-ES')} km · llegada ondas ${dateLocal(r.arrival)}</small></div><span class="risk">${r.screen}/100</span></div>`}).join('')||'<div class="notice">No se recibieron terremotos mundiales importantes.</div>';renderWorldChanges();renderWorldMap();if(!selectedWorld&&es.length)selectWorld(es.slice().sort((a,b)=>remoteMetrics(b).screen-remoteMetrics(a).screen)[0].id)}
/* Módulo "Últimos eventos mundiales": los 5 más recientes por fecha, con el
   mismo diseño que el listado de Granada. La lista de "Grandes terremotos"
   sigue debajo ordenada por magnitud. */
function worldRecentMarkup(e,index=0){const r=remoteMetrics(e),depth=Number.isFinite(e.depth)?e.depth.toFixed(1)+' km':'—',latest=index===0;return `<button class="recentEvent ${worldTone(e.mag)} ${latest?'isLatest':''}" onclick="openWorld('${String(e.id).replaceAll("'","\\'")}')"><div class="recentMagnitude"><span>M</span><strong>${e.mag.toFixed(1)}</strong></div><div class="recentEventBody"><div class="recentEventTop"><b>${safeMapText(e.place||'Localización no disponible')}</b><span class="recentCategory">${worldSeverity(e.mag)}</span>${latest?'<em>ÚLTIMO</em>':''}</div><div class="recentEventMeta"><span><strong>${age(e.time)}</strong> hace</span><span>${dateLocal(e.time)}</span><span>Prof. <strong>${depth}</strong></span><span>${Math.round(r.d).toLocaleString('es-ES')} km de Granada</span><span>${safeMapText(e.source||'USGS')}</span></div></div></button>`}
function renderWorldChanges(){if(!$('worldChangeGrid'))return;const es=world.slice().sort((a,b)=>b.time-a.time).slice(0,5);if($('worldChangeBadge'))$('worldChangeBadge').textContent=es.length?`${es.length} ÚLTIMOS`:'SIN DATOS';$('worldChangeGrid').innerHTML=es.map((e,i)=>worldRecentMarkup(e,i)).join('')||'<div class="notice">No se recibieron eventos mundiales.</div>'}
window.openWorld=id=>{const e=world.find(x=>String(x.id)===String(id));if(!e)return;const btn=document.querySelector('[data-view="world"]');if(btn&&!btn.classList.contains('on'))btn.click();requestAnimationFrame(()=>{const wrap=$('worldMap')?.closest('.mapWrap')||$('worldMap');wrap?.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>{const nav=document.querySelector('.nav'),offset=(nav?.getBoundingClientRect().height||0)+8;window.scrollBy({top:-offset,behavior:'smooth'});ensureWorldMap()?.resize?.();setTimeout(()=>selectWorld(e.id),120)},280)})};
function distRows(data){const mx=Math.max(1,...data.map(x=>x[1]));return data.map(x=>`<div class="distRow"><span>${x[0]}</span><div class="distBar"><i style="width:${x[1]/mx*100}%"></i></div><b>${x[1]}</b></div>`).join('')}
function renderActivityChart(es){const s=$('activityChart'),now=Date.now(),bins=Array(24).fill(0);es.forEach(e=>{const h=(now-e.time)/36e5;if(h>=0&&h<72)bins[23-Math.floor(h/3)]++});const max=Math.max(1,...bins),W=680/24;s.innerHTML='<line class="axis" x1="30" y1="170" x2="710" y2="170"/>';bins.forEach((v,i)=>{const h=v/max*135,x=30+i*W+3,w=W-6;s.insertAdjacentHTML('beforeend',`<rect x="${x}" y="${170-h}" width="${w}" height="${h}" rx="2" fill="${i>=22?'#ffc45f':'#58e6ff'}" opacity="${.35+.65*v/max}"/>`)});s.insertAdjacentHTML('beforeend','<text class="chartLabel" x="30" y="190">−72 h</text><text class="chartLabel" x="350" y="190">−36 h</text><text class="chartLabel" x="685" y="190">ahora</text>')}

function localModelAt(events,t){const mags=events.filter(e=>e.mag>=MC&&e.time<=t&&t-e.time<=72*36e5),e72=mags,e24=mags.filter(e=>t-e.time<=24*36e5),e12=mags.filter(e=>t-e.time<=12*36e5),e6=mags.filter(e=>t-e.time<=6*36e5),prev6=mags.filter(e=>t-e.time>6*36e5&&t-e.time<=12*36e5);const max=e72.length?Math.max(...e72.map(e=>e.mag)):0,depths=e72.map(e=>e.depth).filter(Number.isFinite),med=median(depths),rate6=e6.length/6,rate24=e24.length/24,rate=Math.max(.01,.65*rate6+.35*rate24),accel=prev6.length?e6.length/prev6.length:e6.length?2:1,b=bValue(e72),center=weightedCenterAt(e24.length?e24:e72,t),dists=(e24.length?e24:e72).map(e=>hav(center.lat,center.lon,e.lat,e.lon)),radius=clamp(percentile(dists,.8)||5,3,25),shallow=depths.length?depths.filter(d=>d<=10).length/depths.length:0,rateScore=clamp(e6.length*2.2,0,30),magScore=clamp(Math.max(0,max-2)*10,0,20),accelScore=clamp((accel-1)*10+5,0,15),clusterScore=clamp(15*(1-radius/25),0,15),depthScore=clamp(shallow*10,0,10),score=Math.round(clamp((rateScore+magScore+accelScore+clusterScore+depthScore)*(100/90),0,100));return{e72,e24,e6,prev6,max,med,rate,accel,b,center,radius,shallow,score}}
function weightedCenterAt(es,t){if(!es.length)return{lat:G.lat,lon:G.lon};let sw=0,la=0,lo=0;for(const e of es){const ageH=Math.max(.05,(t-e.time)/36e5),w=(1+Math.max(0,e.mag-MC))*(1/(1+ageH/6));sw+=w;la+=e.lat*w;lo+=e.lon*w}return{lat:la/sw,lon:lo/sw}}
function dnaFromHistoric(m){if(!m)return[0,0,0,0,0,0];return[clamp(m.rate/3,0,1),clamp(m.max/5,0,1),clamp(m.shallow,0,1),clamp(1-m.radius/30,0,1),clamp((m.b||0)/1.8,0,1),clamp(m.accel/2.5,0,1)]}
function similarityScore(a,b){if(!a?.length||!b?.length)return 0;return clamp(100*(1-a.reduce((s,v,i)=>s+Math.abs(v-(b[i]||0)),0)/a.length),0,100)}
function runHistoricalAnalysis(){if(!historyLoaded||!historyLocal.length||!model)return;const start=Math.min(...historyLocal.map(e=>e.time)),end=Math.max(...historyLocal.map(e=>e.time)),rangeDays=(end-start)/864e5,anchors=[];for(let t=start+72*36e5;t<=end-24*36e5;t+=6*36e5)anchors.push(t);let alerts=0,hits=0,falseAlerts=0,totalOutcomes=0,misses=0;for(const t of anchors){const m=localModelAt(historyLocal,t),future=historyLocal.some(e=>e.time>t&&e.time<=t+24*36e5&&e.mag>=3),alert=m.score>=70;if(future)totalOutcomes++;if(alert){alerts++;if(future)hits++;else falseAlerts++}else if(future)misses++}const precision=alerts?100*hits/alerts:0,recall=totalOutcomes?100*hits/totalOutcomes:0;historyMetrics={samples:anchors.length,alerts,hits,falseAlerts,totalOutcomes,misses,precision,recall,rangeDays};if($('backtestMetrics'))$('backtestMetrics').innerHTML=[['Muestras',anchors.length],['Precisión alertas',Math.round(precision)+'%'],['Recall M≥3',Math.round(recall)+'%'],['Falsas alertas',falseAlerts]].map(x=>`<div class="quality"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');if($('backtestNote'))$('backtestNote').innerHTML=`Umbral probado: <b>score ≥70</b>. Hubo ${totalOutcomes} ventanas con al menos un M≥3 en las 24 h siguientes. Aciertos ${hits}, pérdidas ${misses}. Este test no calibra todavía una probabilidad absoluta.`;
const currentDna=dnaFromHistoric(model),cands=[];for(let t=start+72*36e5;t<=end-5*864e5;t+=24*36e5){const m=localModelAt(historyLocal,t);if(m.e72.length<5)continue;cands.push({t,sim:similarityScore(currentDna,dnaFromHistoric(m)),m})}cands.sort((a,b)=>b.sim-a.sim);const best=cands[0];if($('similarityText'))$('similarityText').innerHTML=best?`Patrón histórico más parecido dentro del periodo cargado: <b>${Math.round(best.sim)}% de similitud</b> alrededor del ${new Date(best.t).toLocaleDateString('es-ES')}. Coinciden rasgos estadísticos; no implica que el desenlace vaya a repetirse.`:'No hay suficiente histórico comparable.';
const durH=(end-start)/36e5,baseRate=historyLocal.length/Math.max(1,durH),windows=[[0,6],[6,24],[24,72]],rh=windows.map(([a,b])=>{let obs=0;for(const w of historyWorld.filter(e=>e.mag>=7)){obs+=historyLocal.filter(l=>l.time>=w.time+a*36e5&&l.time<w.time+b*36e5).length}const n=historyWorld.filter(e=>e.mag>=7).length,exp=n*baseRate*(b-a),ratio=exp?obs/exp:0;return{a,b,obs,exp,ratio}});if($('remoteHistory'))$('remoteHistory').innerHTML=rh.map(x=>`<div class="remoteStat"><span>${x.a}–${x.b} h · observado/esperado</span><strong>${x.ratio?x.ratio.toFixed(2)+'×':'N/D'}</strong><div class="forecastLabel">${x.obs} observados · ${x.exp.toFixed(1)} esperados</div></div>`).join('');
renderModelQuality();
}
function renderModelQuality(){if(!model)return;const hist=historyMetrics,liveCount=model.e72.length,bok=!!model.b,coverage=Math.round(clamp((liveCount/25)*100,0,100)),histText=hist?Math.round(hist.rangeDays)+' d':'—',precision=hist?Math.round(hist.precision)+'%':'—';let confidence=liveCount>=30&&bok?'MEDIA-ALTA':liveCount>=15?'MEDIA':'BAJA';$('modelQuality').innerHTML=[['Confianza actual',confidence],['Eventos útiles',liveCount],['Histórico cargado',histText],['Precisión backtest',precision]].map(x=>`<div class="quality"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}
function setHistoryStatus(txt){if($('historyStatus'))$('historyStatus').textContent=txt}
async function loadHistory(force=false){if(historyLoaded&&!force){runHistoricalAnalysis();return}setHistoryStatus('Consultando histórico EMSC + USGS…');try{const j=await getJSON('/api/history?_='+Date.now());if(!j.ok)throw new Error(j.error||'histórico no disponible');historyLocal=j.local||[];historyWorld=j.world||[];historyLoaded=true;setHistoryStatus(`Histórico cargado: ${historyLocal.length} eventos locales · ${historyWorld.length} M≥7 mundiales · ${dateLocal(j.fetchedAt||Date.now())}`);runHistoricalAnalysis()}catch(e){setHistoryStatus('No se pudo cargar el histórico: '+(e.message||e));if($('similarityText'))$('similarityText').textContent='Sin histórico no se puede calcular similitud ni backtesting.';renderModelQuality()}}
async function submitFelt(level){const latest=newest(model?.e72||local);try{const r=await fetch('/api/felt',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({level:Number(level),at:Date.now(),eventId:latest?.id||null,eventMag:latest?.mag||null,region:'Granada'})});if(!r.ok)throw new Error('HTTP '+r.status);toast('Reporte recibido',Number(level)===0?'Has indicado que no lo has sentido.':'Gracias. Se ha añadido a la Red SISMIA.');await loadCommunity()}catch(e){toast('Reporte local','No se pudo enviar al servidor. Guardaré la selección solo en este dispositivo.');try{localStorage.setItem('sismia-felt-last',JSON.stringify({level,at:Date.now()}))}catch(_){}}}
async function loadCommunity(){try{const j=await getJSON('/api/felt?_='+Date.now());const c=j.counts||[0,0,0,0];$('communityStats').innerHTML=[['sin sentir',c[0]||0],['leve',c[1]||0],['claro',c[2]||0],['fuerte',c[3]||0]].map(x=>`<div><b>${x[1]}</b><span>${x[0]}</span></div>`).join('');$('communityNote').textContent=`${j.total||0} reportes anónimos en las últimas 24 h · sin geolocalización precisa.`}catch(e){$('communityNote').textContent='Red SISMIA no disponible ahora mismo.'}}

async function loadSensorNetwork(){try{const j=await getJSON('/api/sensor-network?_='+Date.now());$('sensorNet10').textContent=j.n10??0;$('sensorNet60').textContent=j.n60??0;$('sensorNetConfidence').textContent=(j.confidence??0)+'/100';$('sensorNetBadge').textContent=(j.n10||0)>2?'COINCIDENCIA':'RED';$('sensorNetText').textContent=(j.n10||0)>2?`${j.n10} dispositivos con detección en 10 min. Es una coincidencia de sensores SISMIA, no confirmación sísmica; contrasta con EMSC/IGN.`:'Una sola detección puede ser ruido local. Varias detecciones independientes aumentan el interés, pero requieren contraste con redes oficiales.'}catch(_){}}
async function sendSensorHit(stats){try{await fetch('/api/sensor-network',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({at:Date.now(),rms:stats.rms,peak:stats.peak,gyro:stats.gyro,deviceId:anonDeviceId})});setTimeout(loadSensorNetwork,800)}catch(_){}}
function urlBase64ToUint8Array(base64String){const padding='='.repeat((4-base64String.length%4)%4),base64=(base64String+padding).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base64),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
async function pushStatus(){try{const j=await getJSON('/api/push-subscribe?_='+Date.now());$('serverSubs').textContent=j.subscriptions??'—';$('serverLastRun').textContent=j.lastRun?age(j.lastRun)+' · '+dateLocal(j.lastRun):'sin ejecución';$('serverMonitor').textContent=j.monitor?.ok?'ACTIVO':'ESPERANDO';$('serverBadge').textContent=j.monitor?.ok?'24/7 ACTIVO':'PREPARADO';$('serverPulse').className='serverPulse '+(j.monitor?.ok?'ok':'');if(j.monitor?.lastScore!=null)$('serverNote').innerHTML=`Último score servidor: <b>${j.monitor.lastScore}/100</b> · ${j.monitor.localCount||0} eventos recientes. Estado del backend Vercel.`}catch(e){$('serverMonitor').textContent='SIN RESPUESTA';$('serverBadge').textContent='ERROR';$('serverPulse').className='serverPulse bad'}}
function renderAnalysis(){if(!model)return;
  if($('analysisState'))$('analysisState').textContent=analysisStateLabel();
  if($('aEvents'))$('aEvents').textContent=model.e72.length;
  if($('aB'))$('aB').textContent=model.b?model.b.toFixed(2):'N/D';
  if($('aRadius'))$('aRadius').textContent=model.radius.toFixed(1)+' km';
  if($('analysisMax'))$('analysisMax').textContent=model.max?'M'+model.max.toFixed(1):'—';
  if($('analysisDepth'))$('analysisDepth').textContent=Number.isFinite(model.med)?model.med.toFixed(1)+' km':'—';
  const town=nearestTown(model.center.lat,model.center.lon);if($('alertZone'))$('alertZone').textContent=town.name;
  renderActivityChart(model.e72);
  const md=[['1,5–1,9',0],['2,0–2,9',0],['3,0–3,9',0],['≥4,0',0]];model.e72.forEach(e=>{if(e.mag<2)md[0][1]++;else if(e.mag<3)md[1][1]++;else if(e.mag<4)md[2][1]++;else md[3][1]++});if($('magDist'))$('magDist').innerHTML=distRows(md);
  const dd=[['0–5 km',0],['5–10 km',0],['10–20 km',0],['>20 km',0]];model.e72.forEach(e=>{const d=e.depth;if(!Number.isFinite(d))return;if(d<=5)dd[0][1]++;else if(d<=10)dd[1][1]++;else if(d<=20)dd[2][1]++;else dd[3][1]++});if($('depthDist'))$('depthDist').innerHTML=distRows(dd);
  const trend=model.accel>1.35?`En las últimas 6 horas la actividad está <b>aumentando</b> respecto al bloque anterior (${model.e6.length} frente a ${model.prev6.length} eventos).`:model.accel<.75?`La actividad reciente está <b>disminuyendo</b> (${model.e6.length} eventos en 6 h frente a ${model.prev6.length} en el bloque anterior).`:`El ritmo se mantiene <b>relativamente estable</b>: no aparece un cambio brusco entre los dos últimos bloques de 6 horas.`;if($('analysisTrendText'))$('analysisTrendText').innerHTML=trend;
  renderModelQuality();renderAlerts();
}
function renderAlerts(){if(!model)return;const town=nearestTown(model.center.lat,model.center.lon);let state=model.score>=80?'VIGILANCIA MUY ALTA':model.score>=60?'VIGILANCIA ALTA':model.score>=35?'VIGILANCIA MODERADA':'VIGILANCIA NORMAL';
  if($('alertN'))$('alertN').textContent=model.score;if($('alertBadge'))$('alertBadge').textContent=model.score+'/100';if($('alertState')){$('alertState').textContent=state;$('alertState').className='alertState '+(model.score>=80?'danger':model.score>=60?'watch':'safe')};if($('analysisScoreRing'))$('analysisScoreRing').style.setProperty('--score',model.score);
  if($('alertComponents'))$('alertComponents').innerHTML=Object.entries(model.components).map(([k,v])=>{const max=k==='Actividad reciente'?30:k==='Magnitud máxima'?20:k==='Cambio de ritmo'?15:k==='Concentración espacial'?15:10;return `<div class="comp"><span>${k}</span><div class="track"><div class="fill" style="width:${clamp(v/max*100,0,100)}%"></div></div><b>${v.toFixed(0)}</b></div>`}).join('');
  let why=model.score>=80?'La actividad reciente es muy alta comparada con el patrón que está observando SISMIA.':model.score>=60?'Hay varios indicadores por encima de lo habitual y conviene seguir la evolución.':model.score>=35?'Hay actividad apreciable, pero sin una señal extrema en el conjunto de indicadores.':'La actividad observada encaja con un nivel de vigilancia normal dentro de este modelo.';
  let trend=model.accel>1.35?'El ritmo está aumentando.':model.accel<.75?'El ritmo está bajando.':'El ritmo está estable.';if($('analysisRiskNote'))$('analysisRiskNote').textContent=`${why} ${trend}`;
  if($('analysisConclusion'))$('analysisConclusion').innerHTML=`<b>${state}.</b> En las últimas 72 h hay <b>${model.e72.length} eventos M≥${MC}</b>; el mayor es <b>M${model.max.toFixed(1)}</b> y la actividad se concentra alrededor de <b>${town.name}</b> en un radio aproximado de <b>${model.radius.toFixed(1)} km</b>. ${trend}<br><br><strong>En palabras sencillas:</strong> ${model.score>=60?'hay más señales de actividad de las habituales y merece seguimiento, pero esto no significa que vaya a ocurrir un terremoto mayor.':'los datos actuales no permiten afirmar que vaya a ocurrir un terremoto mayor.'}<br><br><small>Este análisis es experimental y automatizado. No es una predicción ni una alerta oficial. Para decisiones de seguridad, consulta IGN y Protección Civil.</small>`;
  const high=model.score>=80;if(high&&!lastAlertState)triggerAlert('SISMIA detecta actividad muy elevada',state+' · score '+model.score+'/100');lastAlertState=high;pushStatus();
}
function triggerAlert(title,body){document.body.animate([{filter:'none'},{filter:'sepia(1) saturate(4) brightness(1.15)'},{filter:'none'}],{duration:1200});toast('⚠ '+title,body);if(interacted)alarm(false);if('Notification'in window&&Notification.permission==='granted')try{new Notification(title,{body,icon:'/icon.svg'})}catch(_){}}
function alarm(showToast=true){try{let C=window.AudioContext||window.webkitAudioContext,c=new C();[0,.28,.56,.84].forEach((t,i)=>{let o=c.createOscillator(),g=c.createGain();o.frequency.value=i%2?920:680;o.type='square';g.gain.setValueAtTime(.0001,c.currentTime+t);g.gain.exponentialRampToValueAtTime(.16,c.currentTime+t+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+t+.22);o.connect(g).connect(c.destination);o.start(c.currentTime+t);o.stop(c.currentTime+t+.24)});if(showToast)toast('⚠ PRUEBA DE ALERTA','Sonido y señal visual de SISMIA.')}catch(e){toast('Audio bloqueado','Toca de nuevo el botón con el volumen activado.')}}
async function notify(){if(!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window)){toast('Push no disponible','En iPhone instala SISMIA en la pantalla de inicio y ábrela desde su icono.');return}try{const p=await Notification.requestPermission();if(p!=='granted')throw new Error('Permiso de notificaciones no concedido.');const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(VAPID_PUBLIC_KEY)});const r=await fetch('/api/push-subscribe',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({subscription:sub.toJSON(),createdAt:Date.now(),ua:navigator.userAgent.slice(0,180)})});if(!r.ok)throw new Error('Servidor push HTTP '+r.status);$('notifyState').innerHTML='<b>Push registrado.</b> La entrega 24/7 requiere que el backend persistente y el monitor estén activos. iOS controla finalmente la entrega y el sonido.';toast('Push registrado','Este dispositivo se ha enviado al backend SISMIA.');pushStatus()}catch(e){$('notifyState').textContent='No se pudo activar: '+(e.message||e);toast('No se pudo activar Push',e.message||String(e))}}
